### ISSUE TITLE
Unable to see classes in Intellij Idea

### ISSUE THREAD

**Issue by ferozed** [erosb/json-sKema#116]
I have a weird problem. I am using this jar in a gradle project. If I run the gradle project using `gradle` cli, it works fine.

However, in IntelliJ Idea, I am unable to see the classes in the `com.github.erosb.jsonsKema` namespace.

See the attached screenshot

![image](https://github.com/user-attachments/assets/c8e50974-75ac-4c91-9316-f8513efee58b)

Due to this I am unable to code in Intellij. 

![image](https://github.com/user-attachments/assets/8da78bac-ab47-4b06-bf23-66a03f6ce06c)

I noticed that this is built with Kotlin. Do I need to do something in Intellij to enable it to see the classes in that namespace?

I dont know what I am doing wrong.

**Comment by erosb** [comment]
Hello, no additional setup should be necessary. I'd try refreshing gradle dependencies / reloading the project in the gradle tool window.

**Comment by ferozed** [comment]
I have already done all that, many times

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by erosb** [comment]
Can you share a reproducer project for this one? I'm usually testing with the [json-sKema-examples](https://github.com/erosb/json-sKema-examples) project, and it doesn't need any additional configuration when importing into IJ. Also I tried in the recent days with a gradle-based project and there wasn't any problem.

**Comment by erosb** [comment]
Hello @ferozed you can refer to [this project](https://github.com/erosb/kappa) about how to import a gradle project into IJ with json-sKema as a dependency, and compare it with your setup.
