### ISSUE TITLE
SchemaLoader and malformed JSON schema (duplicated property)

### ISSUE THREAD

**Issue by humpfhumpf** [erosb/json-sKema#134]
On version 0.19.0 (and bellow), `SchemaLoader` does not detect when a property is defined twice.
This should be detected as a "malformed" JSON (but allowed by [RFC 8259](https://www.rfc-editor.org/rfc/rfc8259#section-4)).

In this schema, "a" key is defined twice in the JSON object "properties":
```json
        {
          "$schema": "https://json-schema.org/draft/2020-12/schema",
          "type": "object",
          "properties": {
            "a": {
              "type": "string"
            },
            "a": {
              "type": "integer"
            }
          }
        }
```

Reproducer:
```java
import com.github.erosb.jsonsKema.*;

public class App2
{
    public static void main( String[] args )
    {
        JsonValue schemaJson = new JsonParser("""
        {
          "$schema": "https://json-schema.org/draft/2020-12/schema",
          "type": "object",
          "properties": {
            "a": {
              "type": "string"
            },
            "a": {
              "type": "integer"
            }
          }
        }
        """).parse();
        Schema schema = new SchemaLoader(schemaJson).load();
        Validator validator = Validator.forSchema(schema);
        JsonValue instance = new JsonParser("""
        {
            "a": 1
        }
        """).parse();
        ValidationFailure failure = validator.validate(instance);
        System.out.println(failure == null ? "Seems OK..." : "KO!");
    }
}
```

This prints: `Seems OK...`

Interesting articles to read:
* [Stackoverflow](https://stackoverflow.com/a/23195243/28357839) reply about duplicated key on JSON Objects.
* From [JSON Schema spec](https://json-schema.org/draft/2020-12/json-schema-core#name-instance-data-model), §4.2.1: "Since an object cannot have two properties with the same key, behavior for a JSON document that tries to define two properties with the same key in a single object is undefined."

**Comment by erosb** [comment]
Hello @humpfhumpf , thanks for reporting the issue. What do you think, what should be the correct behavior when parsing such json? I'm OK with throwing an exception.

**Comment by humpfhumpf** [comment]
In my opinion, such schema is false, even if RFC say that it is "possible".
Perhaps, a new option on parser/loader could be set to check this situation. With an option, you will keep current behaviour for backward compatibility.
The exception (which probably will inherit from RuntimeException, for backward compatibility) should be thrown earlier you can (in `SchemaLoader.load()`?)

**Comment by erosb** [comment]
I think the easiest would be throwing the exception from JsonParser, so it wouldn't matter if the schema or the instance json would contain duplicate keys. And yes, a RuntimeException subclass should be fine.

**Comment by humpfhumpf** [comment]
thx a lot
