### ISSUE TITLE
SubSchema internal references are not resolved

### ISSUE THREAD

**Issue by bsanchezb** [erosb/json-sKema#16]
Hello,

I have a problem when working with multiple schemas which refer to the internal content.

_NOTE: The test cases below are based on [RefResolutionTest.kt](https://github.com/erosb/json-sKema/blob/master/src/test/kotlin/com/github/erosb/jsonsKema/RefResolutionTest.kt) class._

When working with a root schema referencing its internal variables, the properties are resolved successfully, for instance:
```
    @Test
    fun `ref definitions`() {
        val root: CompositeSchema = createSchemaLoaderForString(
                """
            {
                "$ref": "#/$defs/ddd",
                "$defs": {
                   "ddd": {
                        "title": "my title",
                        "$anchor": "myAnchor"
                   }
                }
            }
            """.trimIndent()
        )() as CompositeSchema
        val actual = root.accept(TraversingSchemaVisitor<String>("$ref", "title"))!!
        assertThat(actual).isEqualTo("my title")
    }
```
Here we refer to "ddd" header directly from the schema and it works well, returning the correct value.

If we want to add a simple subSchema and refer it from the root schema, it works well as well:
```
    @Test
    fun `ref definitions child`() {
        val actual = createSchemaLoaderForString(
                """
                {
                    "$ref": "http://subschema.json#/$defs/ddd"
                }
            """,
                mapOf(
                        Pair(
                                "http://subschema.json",
                                """
                                    {
                                        "$defs": {
                                           "ddd": {
                                                "title": "my title",
                                                "$anchor": "myAnchor"
                                           }
                                        }
                                    }
                                """
                        )
                )
        )() as CompositeSchema

        val referred = (actual.subschemas.iterator().next() as ReferenceSchema).referredSchema as CompositeSchema
        assertThat(referred.title!!.value).isEqualTo("my title")
    }
```

However, if the subSchema uses internal "$ref" reference, that fails as the application is looking for the referenced object in the root schema, and not within the subSchema.
For instance, if we move the schema from the first example to a be a subschema in the second example, it does not longer work:
```
    @Test
    fun `ref definitions child self ref`() {
        val actual = createSchemaLoaderForString(
                """
                {
                    "$ref": "http://subschema.json#/$defs/ddd"
                }
            """,
                mapOf(
                        Pair(
                                "http://subschema.json",
                                """
                                    {
                                        "$ref": "#/$defs/ddd",
                                        "$defs": {
                                           "ddd": {
                                                "title": "my title",
                                                "$anchor": "myAnchor"
                                           }
                                        }
                                    }
                                """
                        )
                )
        )() as CompositeSchema
    }
```
and returns the following error:

```
java.lang.Error: json pointer evaluation error: could not resolve property $defs in {
  "$ref": "http://subschema.json#/$defs/ddd"
}
	at com.github.erosb.jsonsKema.SchemaLoader$evaluateJsonPointer$lookupNext$1.invoke(SchemaLoader.kt:375)
	at com.github.erosb.jsonsKema.SchemaLoader$evaluateJsonPointer$lookupNext$1.invoke(SchemaLoader.kt:366)
	at com.github.erosb.jsonsKema.SchemaLoader.enterScope(SchemaLoader.kt:176)
	at com.github.erosb.jsonsKema.SchemaLoader.evaluateJsonPointer$lookupNext(SchemaLoader.kt:366)
	at com.github.erosb.jsonsKema.SchemaLoader.access$evaluateJsonPointer$lookupNext(SchemaLoader.kt:107)
	at com.github.erosb.jsonsKema.SchemaLoader$evaluateJsonPointer$1.invoke(SchemaLoader.kt:404)
	at com.github.erosb.jsonsKema.SchemaLoader$evaluateJsonPointer$1.invoke(SchemaLoader.kt:403)
	at com.github.erosb.jsonsKema.SchemaLoader.runWithChangedBaseURI(SchemaLoader.kt:412)
	at com.github.erosb.jsonsKema.SchemaLoader.evaluateJsonPointer(SchemaLoader.kt:403)
	at com.github.erosb.jsonsKema.SchemaLoader.resolve(SchemaLoader.kt:353)
	at com.github.erosb.jsonsKema.SchemaLoader.loadSchema(SchemaLoader.kt:305)
	at com.github.erosb.jsonsKema.SchemaLoader.loadRootSchema(SchemaLoader.kt:290)
	at com.github.erosb.jsonsKema.SchemaLoader.invoke(SchemaLoader.kt:184)
```
So it looks like it tries to resolve the "ddd" header from the root schema, when it is defined within the subSchema itself.

Would it be possible to fix the issue as it blocks our project from upgrading from everit library?

Thank you!

Best regards,
Aleksandr.

**Comment by erosb** [comment]
Hello @bsanchezb I have some experimental changes in the [issue-16](https://github.com/erosb/json-sKema/tree/issue-16) branch. It [is passing](https://github.com/erosb/json-sKema/blob/issue-16/src/test/kotlin/com/github/erosb/jsonsKema/RefResolutionTest.kt#L499) on your testcase, but overall I'm hesitant to release it. 

Can you build this branch and do some experimental testing? Or do you need a maven central release instead?

**Comment by bsanchezb** [comment]
Hi @erosb ,

Thank you for taking a look on the issue. I may check it on my side, but probably later, as now I'm very busy with other stuff. 

I will let you know.

Kind regards,
Aleksandr.

**Comment by prabhat2020** [comment]
Hi @erosb ,
I had similar issue for one of my project while migrating from [https://github.com/everit-org
/
[json-schema](https://github.com/everit-org/json-schema)](url). I pulled issue-16 branch and used that library version to build my project.It seems to be working fine. Once @bsanchezb confirms, I would like to have this merged and released to maven central.It would be great help.
Thanks

**Comment by erosb** [comment]
@prabhat2020 I deployed the fix to maven central, you can upgrade to version `0.10.0`:

```
<dependency>
    <groupId>com.github.erosb</groupId>
    <artifactId>json-sKema</artifactId>
    <version>0.10.0</version>
</dependency>
```

**Comment by prabhat2020** [comment]
Thanks @erosb for quick response

**Comment by erosb** [comment]
I hope the previous release fixed the problem for everyone - closing the issue.

**Comment by erosb** [comment]
Hello @bsanchezb , thank you for your feedback.

>  I think it would be nice if ValidationFailure could return a more user-friendly error from a getMessage() method, similarly as it was in everit-json-schema project with a message returned from ValidationException

Can you please elaborate a bit on it? I think the current structure of `ValidationFailure` should be similar to the old  `ValidationException`, at least that was the intention (it is just not an exception, otherwise it is the same). Can you please give me an example schema and json instance, and let me know how to improve the error message? Also, what was your workaround?

I'm really interested in making the new library easier to use.

**Comment by bsanchezb** [comment]
Hello @erosb,

First of all, thank you for the great work on the project!

The _ValidationFailure_ object does not (always) return original cause of the failure, such as line and position of the issue in the JSON or a requirement within the JWS schema. It has a number of _Causes_ and _Schemas_ you need to iterate over in order to access the relevant information.

You may see the [class](https://github.com/esig/dss/blob/develop/specs-jws/src/main/java/eu/europa/esig/jws/ValidationMessage.java) I had to create in order to return a more user-friendly message similar to the old _ValidationException_. You may also take a look on my [unit tests](https://github.com/esig/dss/commit/b6474b88abbd9ce1ece2931e67aa27a4215d6288) I had to slightly change because of the change in the behavior (after transformations applied with my helper class from above). Obviously, I do not expect the same messages to be returned as before, but an easier way to access the information I need would be much appreciated.

KR,
Aleksandr
