### ISSUE TITLE
Don't use java.net.URLDecoder.decode(String, Charset) to lower minimum Android API level from 33

### ISSUE THREAD

**Issue by smanhaeve** [erosb/json-sKema#18]
When using this library, calls to the static method `java.net.URLDecoder.decode(String, Charset)` force a minimum Android API level 33<sup>[1]</sup>.

In order to allow using this library on earlier android api versions, code like the following should be replaced throughout the library:
```diff
-URLDecoder.decode(s, StandardCharsets.UTF_8)
+URLDecoder.decode(s, StandardCharsets.UTF_8.name())
```

---
\[1\]: [https://developer.android.com/reference/java/net/URLDecoder#decode(java.lang.String,%20java.nio.charset.Charset)](https://developer.android.com/reference/java/net/URLDecoder#decode(java.lang.String,%20java.nio.charset.Charset))

**Comment by erosb** [comment]
Thank you, fixed in `master`
