### ISSUE TITLE
Throw SchemaException when loading fails

### ISSUE THREAD

**Issue by FloriNNic** [erosb/json-sKema#24]
Hello,

It would be very useful if a _SchemaException_ (or similar) would be thrown when loading a _Schema_ with errors (such as invalid references, or wrongly used keywords). At the moment, an _Error_ is thrown, which is too generic and also does not provide a JSON pointer (like the previous library). 

Thank you for your great work!

Regards,
Florin

**Comment by erosb** [comment]
Hello @FloriNNic @octavianN , I made improvements to error handling during schema loading in the latest release (0.15.0), example usage is here: https://github.com/erosb/json-sKema-examples/blob/master/src/main/java/com/github/erosb/jsonsKema/examples/LoadingFailureDetails.java

I'm happy if you share any feedback. Thank you.
