### ISSUE TITLE
Fluent schema builders 

### ISSUE THREAD

**Issue by erosb** [erosb/json-sKema#3]

**Comment by tfrancart** [comment]
Hello ! if I understand well the title of this issue, it would enable the same thing as whta is described at https://stackoverflow.com/a/38478478/189723, correct ? Then I would be particularly interested by this feature !

**Comment by erosb** [comment]
Hello @tfrancart this effort is in progress, you can take an early look at the upcoming API in the fluent-builder branch, in this test: https://github.com/erosb/json-sKema/blob/fluent-builders/src/test/kotlin/com/github/erosb/jsonsKema_fluent/SchemaBuilderTest.kt
Any feedback / question / request for changes is welcome.

**Comment by erosb** [comment]
Hello, this was completed in release [0.16.0](https://github.com/erosb/json-sKema/releases/tag/v0.16.0), usage example is [here](https://github.com/erosb/json-sKema?tab=readme-ov-file#schemabuilder-for-dynamic-programmatic-schema-construction).
