### ISSUE TITLE
Set up Dependabot to keep dependencies up to date.

### ISSUE THREAD

**Issue by big-andy-coates** [erosb/json-sKema#31]
Hey @erosb,

I find it generally very useful to make use of GitHub's Dependabot to keep all your project's dependencies up to date.  I know this project doesn't have much in the way of release dependencies, but it can't hurt to automate it.

Happy to help if you want.

**Comment by erosb** [comment]
Hello Andy, yes please, I would be thankful for your help on that!

**Comment by big-andy-coates** [comment]
@erosb with this `dependabot.yml` file now merged I would have expected to see some update PRs, though I've not checked to see if you have outdated dependencies.

You can manually run dependabot by:

1. Go to the "Insights" tab.
2. Click on "Dependency Graph"
3. Go to the "Dependabot" tab.

You should see something like the following:

![image](https://github.com/erosb/json-sKema/assets/8012398/1a256921-1822-42ed-a35f-da8cbc00068c)

The top item ".github/workflows/build.yml"  should be ".github/workflows/maven.yml" for your repo. This job looks to update the version of GitHub actions in your workflow.

The second item "build.gradle.kts" should be "pom.xml" or something similar for your Maven build.  This job looks to update the version of dependencies in your Maven build.  I use Gradle, so don't have specific experience with using Dependabot with Maven, but it says its supported.

**Do you see these two jobs?**

For either of these two jobs you can click the `Recent update jobs` button to see the logs of previous runs.   Both should have run on the 1st of December.

**Are there any previous runs?**

There should also be a "Check for updates" button on each of the job pages.  Clicking this should cause dependabot to run its magic.

Let me know what is & what is not present or working and I'll see if I can help more.

**Comment by erosb** [comment]
Hello @big-andy-coates  thanks for getting back to this. It seems the yaml parser was complaining about the `registries` top-level key being null instead of an empty object. Now the job seems to be running, let's see if it yields any PRs.

**Comment by big-andy-coates** [comment]
Yep, I can see it is :)

I use GitHub workflow to auto-approve and merge dependabot version updates.  You may want to think about doing the same:

https://github.com/creek-service/creek-kafka/blob/main/.github/workflows/dependabot-auto-merge.yml

**Comment by erosb** [comment]
@big-andy-coates thanks for your help, now dependencies are all up to date.
