### ISSUE TITLE
How to resolve schemas with URI

### ISSUE THREAD

**Issue by Gourav2912** [erosb/json-sKema#54]
Hello , I am exploring json-sKema library for schema validation.
I have below schema , how can i resolve city and state json schema during validation.
On validating schema with below data, i expect it to fail validation. But it pass the validation
"{\"firstName\":\"ABC\",\"lastName\":\"ABC\",\"age\":20,\"city\":{\"city1\":{\"name\":20,\"zipCode\":\"45676\"}}}\n"

{

  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string",
      "description": "The citizen's first name."
    },
    "lastName": {
      "type": "string",
      "description": "The citizen's last name."
    },
    "age": {
      "description": "Age in years which must be equal to or greater than zero.",
      "type": "integer",
      "minimum": 0
    },
    "city": {
      "type": "object",
      "properties": {
        "city1": { "$ref": "city.json"},
        "state": {"$ref": "state.json"}
      }

      }

  }
}

city.json {

  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The city's name."
    },
    "zipCode": {
      "type": "integer",
      "description": "The zip code.",
      "minimum": 0
    }
  }
}

state.json {

  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The city's name."
    },
    "zipCode": {
      "type": "integer",
      "description": "The zip code.",
      "minimum": 0
    }
  }
}

**Comment by Gourav2912** [comment]
Below is my java class for same
import com.github.erosb.jsonsKema.IJsonValue;
import com.github.erosb.jsonsKema.JsonParseException;
import com.github.erosb.jsonsKema.JsonParser;
import com.github.erosb.jsonsKema.JsonValue;
import com.github.erosb.jsonsKema.Schema;
import com.github.erosb.jsonsKema.SchemaClient;
import com.github.erosb.jsonsKema.SchemaLoader;
import com.github.erosb.jsonsKema.SchemaLoaderConfig;
import com.github.erosb.jsonsKema.SchemaLoadingException;
import com.github.erosb.jsonsKema.Validator;
import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;
import java.util.stream.Collectors;
import org.junit.Test;

public class ReferenceTest {

  private static final String DUMMY_BASE_URI = "";

  @Test
  public void testReferences() throws Exception {
    String doc = "{\n"
        + "  \"customerName\": \"acme\",\n"
        + "  \"acquireDate\": \"2020-12-12\"\n"
        + "}";
    String data = "{\"firstName\":\"ABC\",\"lastName\":\"ABC\",\"age\":20,\"city\":{\"city1\":{\"name\":20,\"zipCode\":\"45676\"}}}\n";

    JsonValue jsonValue = new JsonParser(data).parse();

    String oneOfSchema = "{\n" +
            "\n" +
            "  \"$schema\": \"http://json-schema.org/draft-07/schema#\",\n" +
            "  \"type\": \"object\",\n" +
            "  \"properties\": {\n" +
            "    \"firstName\": {\n" +
            "      \"type\": \"string\",\n" +
            "      \"description\": \"The citizen's first name.\"\n" +
            "    },\n" +
            "    \"lastName\": {\n" +
            "      \"type\": \"string\",\n" +
            "      \"description\": \"The citizen's last name.\"\n" +
            "    },\n" +
            "    \"age\": {\n" +
            "      \"description\": \"Age in years which must be equal to or greater than zero.\",\n" +
            "      \"type\": \"integer\",\n" +
            "      \"minimum\": 0\n" +
            "    },\n" +
            "    \"city\": {\n" +
            "      \"type\": \"object\",\n" +
            "      \"properties\": {\n" +
            "        \"city1\": { \"$ref\": \"city.json\"},\n" +
            "        \"state\": {\"$ref\": \"state.json\"}\n" +
            "      }\n" +
            "\n" +
            "\n" +
            "      }\n" +
            "\n" +
            "\n" +
            "\n" +
            "\n" +
            "\n" +
            "  }\n" +
            "}";
    String userSchema = "{\n" +
            "\n" +
            "  \"$schema\": \"http://json-schema.org/draft-07/schema#\",\n" +
            "  \"type\": \"object\",\n" +
            "  \"properties\": {\n" +
            "    \"name\": {\n" +
            "      \"type\": \"string\",\n" +
            "      \"description\": \"The city's name.\"\n" +
            "    },\n" +
            "    \"zipCode\": {\n" +
            "      \"type\": \"integer\",\n" +
            "      \"description\": \"The zip code.\",\n" +
            "      \"minimum\": 0\n" +
            "    }\n" +
            "  }\n" +
            "}";
    String customerSchema = "{\n" +
            "\n" +
            "  \"$schema\": \"http://json-schema.org/draft-07/schema#\",\n" +
            "  \"type\": \"object\",\n" +
            "  \"properties\": {\n" +
            "    \"name\": {\n" +
            "      \"type\": \"string\",\n" +
            "      \"description\": \"The city's name.\"\n" +
            "    },\n" +
            "    \"zipCode\": {\n" +
            "      \"type\": \"integer\",\n" +
            "      \"description\": \"The zip code.\",\n" +
            "      \"minimum\": 0\n" +
            "    }\n" +
            "  }\n" +
            "}";

    Map<URI, String> refs = new HashMap<>();
    refs.put(new URI( "city.json"), userSchema);
    refs.put(new URI( "state.json"), customerSchema);

    SchemaLoaderConfig config = new SchemaLoaderConfig(
        new ReferenceSchemaClient(refs), DUMMY_BASE_URI);

    JsonValue schemaJson = new JsonParser(oneOfSchema).parse();

    Schema loadedSchema = new SchemaLoader(schemaJson, config).load();
    Validator validator = Validator.forSchema(loadedSchema);
    validator.validate(jsonValue);
  }

  public static class ReferenceSchemaClient implements SchemaClient {

    private Map<URI, String> references;

    public ReferenceSchemaClient(Map<URI, String> references) {
      this.references = references;
    }

    @Override
    public InputStream get(URI uri) {
      String reference = references.get(uri);
      if (reference == null) {
        throw new UncheckedIOException(new FileNotFoundException(uri.toString()));
      }
      return new ByteArrayInputStream(reference.getBytes(StandardCharsets.UTF_8));
    }

    @Override
    public IJsonValue getParsed(URI uri) {
      BufferedReader reader = new BufferedReader(new InputStreamReader(get(uri)));
      String string = reader.lines().collect(Collectors.joining());
      try {
        return new JsonParser(string).parse();
      } catch (JsonParseException ex) {
        throw new SchemaLoadingException("failed to parse json content returned from $uri", ex);
      }
    }
  }
}

**Comment by bsanchezb** [comment]
Hi,

Could you try instead of:
```
return new JsonParser(string)
```
use
```
return new JsonParser(string, uri)
```
where, _uri_ is the identifier of the schema (but not location of the schema file!).

Like this the _SchemaLoader_ will know about the origin URI of the schema, and will re-use it on references processing.

I had a similar issue when upgrading from everit project, see my last https://github.com/erosb/json-sKema/issues/16#issuecomment-1893545091.
But I do not know whether it is indented behavior or not.

I hope it will help you.

Best regards,
Aleksandr
