### ISSUE TITLE
Visibility of SchemaClient classes

### ISSUE THREAD

**Issue by Mairu** [erosb/json-sKema#94]
We have the use case that we want to parse openapi yaml specification with references to other yaml files and potential json files.
Therefore I created a custom SchemaClient which transform the yaml files into json and using the JsonParser afterwards.
For non yaml files I would want to delegate to the a SchemaClient based on the classes of this package.

`new MemoizingSchemaClient(new ClassPathAwareSchemaClient(new DefaultSchemaClient()))`

But this is not working because they are marked as internal. (So I had to copy them, which of course has drawbacks)
So my question is, is there a reason why this is the case or can they be made public available to be used?

**Comment by Mairu** [comment]
Okay, I canget the default client by using `SchemaLoaderConfig.createDefaultConfig(Map.of()).getSchemaClient()` which is sufficient for my use case.

So if they should stay internal, the issue can be closed.

**Comment by erosb** [comment]
Hello @Mairu , thank you for opening this issue. I'm interested in improving support for OpenAPI-related usecases.

> We have the use case that we want to parse openapi yaml specification with references to other yaml files and potential json files.

What was your requirement, more precisely? Did you use any other library for processing the OpenAPI yaml?

> Therefore I created a custom SchemaClient which transform the yaml files into json and using the JsonParser afterwards.

Have you considered first converting the whole yaml into json in the first place, before calling this library?

**Comment by Mairu** [comment]
Hello @erosb,

our use case is quite simple, we are writing our OpenAPI specifications as yaml files and wanted to add our validation rules into our specs.
As we have not just a single file, but multiple ones with references to a others we wanted to use the already existing function of your library to load references.

In the end our yaml aware schema client is very simple, it is a wrapper around your (default) client with an overridden getParsed method that handles urls ending with ya?ml by using Jackson to transform it to json before using the JsonParser and parse it, all others are delegated to the defaultClient.

**Comment by erosb** [comment]
@Mairu that's interesting. I would try solving this (instead of extracting the necessary json schemas from the OpenAPI):
 * convert the OpenAPI yaml into json
 * at the root level of the resulting json, add a `"$ref": "#/paths/.../path/to/your/schema"`
 * for the other referenced yaml files: also convert them into json, and [pre-registering them](https://github.com/erosb/json-sKema?tab=readme-ov-file#pre-registering-schemas-by-uri-before-schema-loading)
 * validate the json with its root-level `$ref`

(just an idea, not sure if it would work better than your solution)

**Comment by erosb** [comment]
Hello @Mairu version [0.19.0](https://github.com/erosb/json-sKema/releases/tag/v0.19.0) now supports loading YAML content as JSON Schema out of the box, you don't need to write any customized `SchemaClient` for that purpose. Or, in case you still need for any other reason, you can have a custom `SchemaClient` which uses `SchemaClient.createDefaultSchemaClient()` as fallback.

**Comment by Mairu** [comment]
I think with 0.19.0 the issue can be closed, thanks!
